#' Location of NOAA Stations.
#'
#' This data is generated by the rnoaa package.
#' 
#' # NOAAstations <- ghcnd_stations() # Takes a while to run
#' 
#' # save(NOAAstations, "NOAAstations.rda")
#' 
#' This data is up to date as of July 2018
#'
#' @format dataframe
#' \describe{
#'   ...
#' }
"NOAAstations"